import json
from pathlib import Path
import pytest
from quorlen import (
    TextWorthinessScorer,
    load_default_lexicon,
    QuorlenResult,
    QuorlenResultHits,
    QuorlenResultMeta
)

@pytest.fixture
def scorer():
    config = load_default_lexicon()
    return TextWorthinessScorer(config)

def test_cross_language_parity(scorer):
    # Load expected results generated by the reference JavaScript engine
    results_path = Path(__file__).parent / "expected_results.json"
    if not results_path.exists():
        script_path = Path(__file__).parents[2] / "javascript" / "scripts" / "extract_expected.js"
        if script_path.exists():
            import subprocess
            subprocess.run(["node", str(script_path)], check=True)

    assert results_path.exists(), f"expected_results.json not found at {results_path}"

    with open(results_path, "r", encoding="utf-8") as f:
        expected_samples = json.load(f)

    for idx, expected in enumerate(expected_samples):
        text = expected["text"]
        result = scorer.score(text)

        # Check main properties
        assert result.score == expected["score"], (
            f"Mismatch at sample #{idx + 1} ('{text[:30]}...'): "
            f"Expected score {expected['score']}, got {result.score}"
        )
        assert result.tier == expected["tier"], (
            f"Mismatch at sample #{idx + 1} ('{text[:30]}...'): "
            f"Expected tier {expected['tier']}, got {result.tier}"
        )
        assert result.lexicon == expected["lexicon"], (
            f"Mismatch at sample #{idx + 1} ('{text[:30]}...'): "
            f"Expected lexicon score {expected['lexicon']}, got {result.lexicon}"
        )
        assert result.structure == expected["structure"], (
            f"Mismatch at sample #{idx + 1} ('{text[:30]}...'): "
            f"Expected structure score {expected['structure']}, got {result.structure}"
        )

        # Check metadata
        assert result.meta.wordCount == expected["meta"]["wordCount"], (
            f"Word count mismatch at sample #{idx + 1}: "
            f"Expected {expected['meta']['wordCount']}, got {result.meta.wordCount}"
        )
        assert result.meta.uniqueWordCount == expected["meta"]["uniqueWordCount"], (
            f"Unique word count mismatch at sample #{idx + 1}: "
            f"Expected {expected['meta']['uniqueWordCount']}, got {result.meta.uniqueWordCount}"
        )
        assert result.meta.sentenceCount == expected["meta"]["sentenceCount"], (
            f"Sentence count mismatch at sample #{idx + 1}: "
            f"Expected {expected['meta']['sentenceCount']}, got {result.meta.sentenceCount}"
        )
        assert result.meta.lexicalDiversity == expected["meta"]["lexicalDiversity"], (
            f"Lexical diversity mismatch at sample #{idx + 1}: "
            f"Expected {expected['meta']['lexicalDiversity']}, got {result.meta.lexicalDiversity}"
        )

        # Check hits (ignore order)
        assert set(result.hits.critical) == set(expected["hits"]["critical"]), (
            f"Critical hits mismatch at sample #{idx + 1}: "
            f"Expected {expected['hits']['critical']}, got {result.hits.critical}"
        )
        assert set(result.hits.high) == set(expected["hits"]["high"]), (
            f"High hits mismatch at sample #{idx + 1}: "
            f"Expected {expected['hits']['high']}, got {result.hits.high}"
        )
        assert set(result.hits.medium) == set(expected["hits"]["medium"]), (
            f"Medium hits mismatch at sample #{idx + 1}: "
            f"Expected {expected['hits']['medium']}, got {result.hits.medium}"
        )

def test_empty_and_invalid_inputs(scorer):
    # None, empty string, whitespace only
    for bad_input in [None, "", "   ", "\n\t"]:
        res = scorer.score(bad_input)
        assert res.score == 0.0
        assert res.tier == "Routine"
        assert res.lexicon == 0.0
        assert res.structure == 0.0
        assert res.hits.critical == []
        assert res.hits.high == []
        assert res.hits.medium == []
        assert res.meta.wordCount == 0
        assert res.meta.uniqueWordCount == 0
        assert res.meta.sentenceCount == 0
        assert res.meta.lexicalDiversity == 0.0

def test_options_alpha_override():
    config = load_default_lexicon()
    
    # Scorer with default alpha
    scorer_default = TextWorthinessScorer(config)
    res_default = scorer_default.score("I graduated today.")
    
    # Scorer with custom alpha override in options
    scorer_custom = TextWorthinessScorer(config, {"alpha": 10.0})
    res_custom = scorer_custom.score("I graduated today.")
    
    # Custom alpha (larger) should suppress scaling, giving lower score
    assert res_custom.score < res_default.score

def test_result_as_dict(scorer):
    res = scorer.score("I got promoted today.")
    res_dict = res.to_dict()
    
    assert isinstance(res_dict, dict)
    assert res_dict["score"] == res.score
    assert res_dict["tier"] == res.tier
    assert res_dict["meta"]["wordCount"] == res.meta.wordCount
    assert res_dict["hits"]["critical"] == res.hits.critical
